# Plan por killer. s = salida recomendada (criterio propio, a partir de las reglas y el foro).
# ojo = amenaza principal y como neutralizarla. src: de donde sale el "ojo".
P = {
 "Hans": dict(s="A o C", por="Es lento y no tiene reglas propias: tienes tiempo para montar la economía. Si hay víctimas agrupadas, la C lo deja clavado en bloodlust bajo.",
   ojo="Pega muchísimo y apuñala gratis a quien tenga al lado. Lleva uno o dos Guard y nunca acabes el turno en su casilla. Puedes ganarle la carrera y saquear la punta del mapa antes de que llegue.", src="foro"),
 "Geppetto": dict(s="B", por="No puedes matarlo mientras queden sus 3 títeres, así que no hay prisa por el arma: primero limpiar minions.",
   ojo="Immortal Master: quita títeres antes de intentar rematarlo. Y cuidado al buscar, las trampas de objeto aquí son desagradables: busca solo lo necesario.", src="foro"),
 "Inkanyamba": dict(s="C", por="Se vuelve más peligroso cuanto más dura la partida (sube su Killer Wrath): la partida larga le favorece a él.",
   ojo="Su Ira se suma a la Ira Divina de Sacred Groves y actúan a la vez. Es la caja más dura del juego; si quieres jugarlo sin sufrir, sácalo de su mapa.", src="foro"),
 "Dr. Fright": dict(s="B", por="Uno de los killers más fáciles según los datos. Salida por defecto.",
   ojo="Necesitas la carta Convince para entrar en casas ocupadas: tenla en cuenta al planificar la ruta de rescate. Mundo de los sueños y Boiler Room cambian dónde estás.", src="reglas"),
 "Poltergeist": dict(s="C", por="No tiene vida y no se le puede hacer daño. Se gana encontrando a Carolyn y saliendo con ella.",
   ojo="Las armas y las cartas de ataque no valen nada aquí. Es la única caja donde buscar arma es tiempo tirado: todo a movimiento, búsqueda y rescate. Nunca la salida D.", src="foro"),
 "Terror from Above": dict(s="B", por="Formato corto y sin monstruo único: no hay un cuerpo al que hacer burst.",
   ojo="Es una bandada. Hay poca información contrastada de esta película; guíate por los datos de Dark Powers y Finales de abajo.", src="poca"),
 "Evomorph": dict(s="C", por="Evoluciona matando. Cada víctima salvada es una evolución que no hace.",
   ojo="Tiene victorias alternativas: autodestruir la nave y escapar, o echarlo por una esclusa. Si la pelea se te tuerce, cambia de objetivo en vez de insistir.", src="foro"),
 "The Intruders": dict(s="B", por="Son tres cuerpos de 6 de vida que cubren el tablero a la vez: no hay ventana segura para regalar el turno 1.",
   ojo="Uno de los tres es siempre el activo y va cambiando. Tiene sistema propio para fabricar armas. Las partidas perdidas se pierden pronto: con Finale sin revelar solo se gana el 28%, así que sobrevivir a los primeros turnos es la clave.", src="reglas+datos"),
 "Ratchet Lady": dict(s="C", por="No te persigue ella, te manda maniacos. Movilidad y rescate rápido.",
   ojo="Se cura sin tope mientras no la ataques, y los Maniacs hacen pérdida directa de vida que NO se bloquea con Guard ni Retaliate. Las defensivas sirven poco: lleva siempre un ataque a mano.", src="foro"),
 "The Organism": dict(s="C", por="Las víctimas se infectan y mutan en killers independientes. Testarlas pronto es rescatar.",
   ojo="Testa cuanto antes a las dos víctimas expuestas más cercanas al laboratorio y deja que la tercera mute sola. Mantén un organismo vivo a poca vida: te da el dado de adrenalina. Con un organismo se gana el 87%; con tres, el 54%. El hacha es ideal. Puedes mandar víctimas al helicóptero por radio sin estar allí.", src="foro+datos"),
 "Big Bad Wolf": dict(s="B o D", por="Tablero pequeño: el arma suele estar cerca. Empieza en modo Track y pasa a Slay al revelarse el Dark Power.",
   ojo="Su Dark Power A Killing Machine anula el daño de Retaliate y de cualquier reacción que devuelva golpes (sigue bloqueando, pero no le haces nada). Si sale, el burst de la sección 03 ya no funciona: cambia el plan a ataques en tu fase.", src="foro"),
 "Terror from the Grave": dict(s="B", por="Género zombi: la presión viene del número, no de un enemigo fuerte.",
   ojo="El Dark Power Legion es de los peores del juego (38% de victorias). Hay poca información contrastada de esta película.", src="poca"),
 "Tormentor": dict(s="D", por="No aparece en el tablero hasta el Finale: tienes toda la primera parte para armarte y montar el burst.",
   ojo="Antes del Finale solo hay trampas mortales que desactivar. Aprovecha ese tiempo para tener arma y mano preparadas cuando salga.", src="reglas"),
 "Razorface": dict(s="B", por="Empiezas con 3 Afflictions encima: la partida va de purgarlas, no de correr.",
   ojo="Para matarlo de verdad hay que purgar cada Affliction cumpliendo su requisito. El Dark Power Life Drain es el peor de la caja (43%).", src="reglas+datos"),
 "Slayer": dict(s="B", por="11 de vida, el saco más grande de su serie: pelea larga, mejor sin regalar turnos.",
   ojo="Hay una dimensión espejo oculta, versión paralela de cada casilla, y misiones con recompensas a elegir. El Finale Your Time is Up es el más duro (46%).", src="reglas+datos"),
 "Hunter": dict(s="C", por="Hay una víctima VIP, el Salvador, a la que hay que proteger.",
   ojo="Dos fases: Mark V y Mark X, con stats distintos. Sus 15 de vida solo cuentan para el Mark X; el daño al Mark V le arranca piezas antes de pasar de fase.", src="reglas"),
 "The Eyeless": dict(s="B", por="Caza por sonido: cuanto menos hagas al principio, menos lo atraes.",
   ojo="Tus propias acciones generan ruido, lo atraen y lo activan. Planifica qué acciones haces y dónde.", src="reglas"),
 "Terror from Destiny": dict(s="B", por="No hay cuerpo al que atacar: el peligro es la cadena de accidentes. Es la película con más victorias (80%).",
   ojo="Hay poca información contrastada de esta película.", src="poca"),
 "Billy": dict(s="C", por="Sus Buddies actúan antes que él y lo protegen: no puedes atacarlo con un Buddy en su casilla.",
   ojo="Se cura cada fase mientras quede activa 1 de las 4 fuentes de energía. Gasta tiempo en desactivarlas pronto. Ojo al Finale épico: saca a Boris y hay que matar a los dos.", src="reglas"),
 "Grimlash": dict(s="C", por="Cada víctima que cae le suma Harvest Madness, y los niños secuestran víctimas para el altar.",
   ojo="Pasar del nivel 3 de Locura es derrota instantánea. Un corazón cura O baja locura, nunca las dos: vigila la pista antes de curarte.", src="reglas"),
 "Berith": dict(s="B", por="Victoria en dos partes: derrotar a Ursula y luego revivirla con Divine Blessings.",
   ojo="Colocar las 14 fichas de Malicia es derrota instantánea, y las casillas de Malicia cambian tu dado por el maldito. Hay que expulsarlo sin matarla.", src="reglas"),
 "Volk'ar": dict(s="B", por="Movimiento oculto con mazo de rutas: no sabes dónde está hasta que lo revelas.",
   ojo="Un ataque acertado revela su ruta; uno fallado dispara la emboscada. Ataca solo con buenas probabilidades (sección 05).", src="reglas"),
 "Raptors": dict(s="C", por="El T-Rex come en orden fijo: víctimas primero. Rescatar cuesta 1 tiempo extra, así que planifica.",
   ojo="La vida de la manada es el número de raptors, sin tope. El T-Rex no se puede matar y mueve 2 por ronda. Las vallas eléctricas bloquean movimiento y tiro según un dado en Upkeep.", src="reglas"),
 "Terror from Beyond": dict(s=None, por=None,
   ojo="Sin información contrastada todavía. Solo datos de partidas.", src="poca"),
 "Krampus": dict(s="B", por="Su fase encadena mucho: ataca, vuelve a elegir objetivo, se mueve y deja un regalo.",
   ojo="Los regalos tienen efecto aleatorio bueno o malo y puedes arriesgarte a abrirlos. El Finale Past Midnight es de los peores del juego (39%). Trae su propio vehículo, el reno.", src="reglas+datos"),
 "Mort": dict(s="C", por="Las víctimas no entran en pánico hasta que se le desenmascara: es tu ventana de rescate.",
   ojo="Está escondido entre 10 sospechosos. Interrogar y Coaccionar eliminan sospechosos; mientras tanto, ciertas cartas de Terror dejan actuar como killer a un sospechoso al azar.", src="reglas"),
}
